/* automatically generated by rust-bindgen 0.57.0 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod std {
        #[allow(unused_imports)]
        use self::super::super::root;
    }
    pub mod __gnu_cxx {
        #[allow(unused_imports)]
        use self::super::super::root;
    }
    pub type size_t = ::std::os::raw::c_ulong;
    pub type __uint16_t = ::std::os::raw::c_ushort;
    extern "C" {
        pub fn execute(t: root::size_t, prover: bool, port_number: u16) -> ::std::os::raw::c_int;
    }
}
